<?php
namespace app\models;
use yii\db\ActiveRecord;

class ScoreInfo extends ActiveRecord
{
    public function attributes()
    {
        return [
            'english',
            'chinese',
            'math',
            'stu_id',
            'id',
        ];
    }
    public static function scoreInfo()
    {
        return 'score_info'; // TODO: Change the autogenerated stub
    }

    public function getStudent()
    {
        return $this->hasOne(StudentInfo::className(),['stu_id'=>'id']);
    }
}